//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFetcher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurrencyExchangeEntities : DbContext
    {
        public CurrencyExchangeEntities()
            : base("name=CurrencyExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BestRate> BestRates { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DataSource> DataSources { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
    }
}
