//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFetcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSource
    {
        public byte Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool IsNew { get; set; }
        public string DataElementName { get; set; }
    }
}
